/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sound_main_Sound */

#ifndef _Included_sound_main_Sound
#define _Included_sound_main_Sound
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sound_main_Sound
 * Method:    hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sound_main_Sound_hello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
